---
title: "Research"
output:
  html_document:
    toc: false
    toc_float: true
    css: research_style.css
---

---

### Historical Political Economy

---

What Counts as a State? Measuring State Development and Fragmentation in Europe (with Anna Grzymala-Busse)

<a href="https://www.dropbox.com/scl/fi/4l5swlpgqwu6r2v8b9q28/draft_states_jan_2025.pdf?rlkey=s1cvk50l2n13dl406t69jzbn7&dl=0">DRAFT</a>

<details>
  <summary><strong>Abstract</strong></summary>
  <p>
A broad scholarly consensus supports the notion of European state development as a model for the emergence of modern nation-states, setting the stage for the creation of the international state system. Yet despite numerous scholarly accounts seeking to explain the developmental trajectory of the European state, there is disagreement about fundamental concepts, including what counts as “Europe” and a common definition for which polities qualify as “states.” This paper examines both, with the goal of exploring the implications of different definitions of the European state for our understanding of political development.  We give special consideration to political fragmentation, long viewed as a critical prerequisite for Europe’s development of proto-democratic and growth-promoting political institutions. We find that the distinct measures lead to very different conclusions about state development, undermining the idea of European state formation as a uniform process. There is no single "Europe" with a single type of "state." 
  </p>
</details>

<br>

Conflict Technology as a Catalyst of State Formation (with Michael-David Mangini)

<a href="https://www.dropbox.com/scl/fi/hs2quow5zqmx183q3b3ln/walls-draft.pdf?rlkey=ivv8kxkep4sk1iur7w73zq2pb&dl=0" class="button1">DRAFT</a>

<details>
  <summary><strong>Abstract</strong></summary>
  <p>
We argue that the gunpowder revolution in medieval Europe encouraged the amalgamation of smaller polities into larger centralized states. The shock to military technology made existing fortifications obsolete and dramatically raised the cost of defensive investments. Small polities lacked the fiscal capacity to make these investments, so they had either to ally or merge with others. Alliances created prospects of free-riding by interior cities on border cities. In contrast, unitary centralized states benefited from geographic and fiscal economies of scale, facilitating defensive investments at the border that protected the interior while limiting free-riding and resource misallocation. Using a new dataset on fortifications in over 6,000 European cities, we find that states made defensive investments in areas of territorial contestation, closer to borders, and farther from raw building materials. These findings are consistent with the theory that large centralized states arose in part as a consequence of changes in military technology.
  </p>
</details>

<br>

The Incentives of Scientific Experts: Evidence from the History of Public Health (conditionally accepted at Quarterly Journal of Political Science)

<a href="https://www.dropbox.com/scl/fi/og16ig7xyu5ur42efg24k/website_cholera_fall_2025.pdf?rlkey=a5pjump694f2fiy0vn0s2qvjr&dl=0" class="button1">DRAFT</a>

<details>
  <summary><strong>Abstract</strong></summary>
  <p>
I examine the dual roles of experts – on one hand, as scholars responsible to a community of their expert peers, and on the other hand, as interested advisors to policymakers – using  evidence from a large corpus of nineteenth-century medical research on cholera. Experts with links to Britain’s overseas trade sector were less likely than experts without such connections to advance theories that cholera was a contagious disease (which had costly implications for British commerce). This difference is driven by the early part of the century, when a scientific consensus around how cholera spreads had not yet solidified. I argue that conflicted experts are more likely to act on their bias in low-information environments, when revealing new information can have a larger impact on policy. As a consensus forms, the value of hiding unfavorable information decreases, and even conflicted experts will reveal what they know to gain scientific credit.
  </p>
</details>

<br>

The Origins of Women’s Political Capital in the Separate Sphere (conditionally accepted at Comparative Political Studies)

<a href="https://www.dropbox.com/scl/fi/x3l7bqb78nf8ltkvqz3ok/cholera_july_2025.pdf?rlkey=4r2sszwamqbelqkcoup43sdrm&dl=0" class="button1">DRAFT</a>

<details>
  <summary><strong>Abstract</strong></summary>
  <p>
I use novel data on women's volunteer organizations during the American Civil War to measure the relationship between social capital in a sex-segregated environment and political capacity. Towns and counties with volunteer groups that leveraged women's domestic labor to support the war effort were more likely to hold women-led marches against the sale of alcohol a decade later. Evidence suggests that the development a leadership class was an important mechanism by which women’s social ties could enable political expression, and that there were strong complementarities between local social capital and regional networks. I also document a link between wartime volunteer clubs and the suffrage movement of the late nineteenth and twentieth centuries. These findings point to the usefulness of social ties as a tool for empowering women, even in a context in which women spend most of their time in the domestic sphere and are precluded from participation in mixed-sex activities.
  </p>
</details>

<br>

---

### Other Research in Political Economy

---

Adjemian, Michael K., Michel Robe, and Casey Petroff. (April 2026) <a href="https://www.sciencedirect.com/science/article/pii/S0261560626000379" class="button1">"Export Bans and Volatility Expectations in Grain Markets." </a> *Journal of International Money and Finance* 164:103552.

<details>
  <summary><strong>Abstract</strong></summary>
  <p>
Accounting for political risk helps to explain commodity price dynamics. Our theory ties commodity price uncertainty both to the likelihood of future export restrictions (i.e., to a dimension of political uncertainty) and to the actual banning of exports (i.e., to the realization and not just the fear of a ban). The channel is the lesser diversification of world supply risk following the imposition of an export ban by a large producer (or export restrictions by numerous small countries). The evidence is consistent with the theory. To test our theoretical model’s insights, we carry out the first high-frequency empirical analysis of bans’ impact on world price dynamics. We construct a novel daily dataset of major restrictions on agricultural exports announced, adopted, or repealed in 2002–2019. We use commodity option-implied volatilities (IVols) as a proxy for price uncertainty. Our empirical framework controls for known drivers of commodity market uncertainty, including global macroeconomic uncertainty and risk aversion (jointly captured by the VIX) and pre-ban spot market tightness (accounting for the state of grain inventories). We document that wheat and corn IVols are higher on the day and week when a ban is first imposed and during the period when it remains in effect. The increase is statistically and economically significant.
  </p>
</details>


